name: "Publish to npm"
description: "Publish package to npm with provenance"

inputs:
  npm-token:
    description: "npm access token for publishing"
    required: true
  registry-url:
    description: "npm registry URL"
    required: false
    default: "https://registry.npmjs.org/"
  dry-run:
    description: "Run npm publish with --dry-run (no package is actually published)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: "Setup Node Environment"
      uses: braintree/web-sdk-github-actions/actions/setup-node@d08e2700fb9ffdfe87200621e25ad63e47014941
      with:
        registry-url: ${{ inputs.registry-url }}
        cache: npm
        install-dependencies: true

    - name: "Publish to npm"
      run: npm publish --provenance ${{ inputs.dry-run == 'true' && '--dry-run' || '' }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
      shell: bash
