[versions]
agp = "8.7.1"
kotlin = "2.2.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntime = "2.8.7"
activityCompose = "1.8.0"
composeBom = "2024.04.01"
navigationCompose = "2.7.5"
payPalSdk = "2.3.0"
androidxBrowser = "1.7.0"
androidHilt = "2.57"
ksp = "2.2.0-2.0.2"
hiltNavigationCompose = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntime" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntime" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser"}
paypal-webpayments = { group = "com.paypal.android", name = "paypal-web-payments", version.ref = "payPalSdk" }
paypal-cardpayments = { group = "com.paypal.android", name = "card-payments", version.ref = "payPalSdk" }
paypal-paymentbuttons = { group = "com.paypal.android", name = "payment-buttons", version.ref = "payPalSdk" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "androidHilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "androidHilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "androidHilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }


